// This file was generated using Gnometa
// https://github.com/djdeath/gnometa
let GenericMatcher=objectThatDelegatesTo(OMeta,{
"notLast":function(){var $elf=this,$vars={},$r0=this._startStructure(0, true);$vars.rule=this._getStructureValue(this.anything());$vars.r=this._appendStructure($r0,this._apply($vars.rule),4);this._appendStructure($r0,this._lookahead(function(){return this._forwardStructure(this._apply($vars.rule),9);}),7);$r0.value=$vars.r;return this._endStructure($r0);}});let BaseStrParser=objectThatDelegatesTo(OMeta,{
"string":function(){var $elf=this,$vars={},$r0=this._startStructure(13, true);$vars.r=this._appendStructure($r0,this.anything(),16);this._pred(((typeof $vars.r) === "string"));$r0.value=$vars.r;return this._endStructure($r0);},
"char":function(){var $elf=this,$vars={},$r0=this._startStructure(21, true);$vars.r=this._appendStructure($r0,this.anything(),24);this._pred((((typeof $vars.r) === "string") && ($vars.r["length"] == (1))));$r0.value=$vars.r;return this._endStructure($r0);},
"space":function(){var $elf=this,$vars={},$r0=this._startStructure(29, true);$vars.r=this._appendStructure($r0,this._apply("char"),32);this._pred(($vars.r.charCodeAt((0)) <= (32)));$r0.value=$vars.r;return this._endStructure($r0);},
"spaces":function(){var $elf=this,$vars={},$r0=this._startStructure(37, true);$r0.value=this._appendStructure($r0,this._many(function(){return this._forwardStructure(this._apply("space"),40);}),38);return this._endStructure($r0);},
"digit":function(){var $elf=this,$vars={},$r0=this._startStructure(42, true);$vars.r=this._appendStructure($r0,this._apply("char"),45);this._pred((($vars.r >= "0") && ($vars.r <= "9")));$r0.value=$vars.r;return this._endStructure($r0);},
"lower":function(){var $elf=this,$vars={},$r0=this._startStructure(50, true);$vars.r=this._appendStructure($r0,this._apply("char"),53);this._pred((($vars.r >= "a") && ($vars.r <= "z")));$r0.value=$vars.r;return this._endStructure($r0);},
"upper":function(){var $elf=this,$vars={},$r0=this._startStructure(58, true);$vars.r=this._appendStructure($r0,this._apply("char"),61);this._pred((($vars.r >= "A") && ($vars.r <= "Z")));$r0.value=$vars.r;return this._endStructure($r0);},
"letter":function(){var $elf=this,$vars={},$r0=this._startStructure(66, true);$r0.value=this._appendStructure($r0,this._or(function(){return this._forwardStructure(this._apply("lower"),69);},function(){return this._forwardStructure(this._apply("upper"),71);}),67);return this._endStructure($r0);},
"letterOrDigit":function(){var $elf=this,$vars={},$r0=this._startStructure(73, true);$r0.value=this._appendStructure($r0,this._or(function(){return this._forwardStructure(this._apply("letter"),76);},function(){return this._forwardStructure(this._apply("digit"),78);}),74);return this._endStructure($r0);},
"token":function(){var $elf=this,$vars={},$r0=this._startStructure(80, true);$vars.tok=this._getStructureValue(this.anything());this._appendStructure($r0,this._apply("spaces"),83);$r0.value=this._appendStructure($r0,this.seq($vars.tok),85);return this._endStructure($r0);},
"listOf":function(){var $elf=this,$vars={},$r0=this._startStructure(88, true);$vars.rule=this._getStructureValue(this.anything());$vars.delim=this._getStructureValue(this.anything());$r0.value=this._appendStructure($r0,this._or(function(){var $r1=this._startStructure(94);$vars.f=this._appendStructure($r1,this._apply($vars.rule),97);$vars.rs=this._appendStructure($r1,this._many(function(){var $r2=this._startStructure(103);this._appendStructure($r2,this._applyWithArgs("token",$vars.delim),105);$r2.value=this._appendStructure($r2,this._apply($vars.rule),108);return this._endStructure($r2);}),101);$r1.value=[$vars.f].concat($vars.rs);return this._endStructure($r1);},function(){var $r1=this._startStructure(93);$r1.value=[];return this._endStructure($r1);}),92);return this._endStructure($r0);},
"fromTo":function(){var $elf=this,$vars={},$r0=this._startStructure(113, true);$vars.x=this._getStructureValue(this.anything());$vars.y=this._getStructureValue(this.anything());$r0.value=this._appendStructure($r0,this._consumedBy(function(){var $r1=this._startStructure(119);this._appendStructure($r1,this.seq($vars.x),121);this._appendStructure($r1,this._many(function(){var $r2=this._startStructure(126);this._appendStructure($r2,this._not(function(){return this._forwardStructure(this.seq($vars.y),130);}),128);$r2.value=this._appendStructure($r2,this._apply("char"),133);return this._endStructure($r2);}),124);$r1.value=this._appendStructure($r1,this.seq($vars.y),135);return this._endStructure($r1);}),117);return this._endStructure($r0);}})

